### ISSUE TITLE
Colocar o css #4

### ISSUE THREAD

**Issue by Vinicius-campos** [IgorPereira98/ProjetoBinho#4]
@juliabraganholli

**Comment by juliabraganholli** [comment]
:+1:

**Comment by IgorPereira98** [comment]
:+1:

**Comment by Vinicius-campos** [comment]
:+1:

**Comment by Vinicius-campos** [comment]
Campo 1 formatado 03dc6c5cdd262d55a9f7f772451ecebbe1eda8db

**Comment by Vinicius-campos** [comment]
Campo 2 formatado 095a4fda6dbb7bea17537a618456dedd605aa847

**Comment by Vinicius-campos** [comment]
Botão Enviar  9eb89c24ab578cce9d74bf63da98514767091072
